name: build_mcdr
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.10.2'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pipenv'
    - run: pipenv install
    - run: mkdir output
    - run: python -m mcdreforged pack -o output --name psmb_chatbridge.mcdr
    - name: Upload notes
        uses: actions/upload-artifact@v2
        with:
          name: psmb_chatbridge.mcdr
          path: output/psmb_chatbridge.mcdr